["Temporada", 
 "Folio", 
 "Indice", 
 "Estado", 
 "Fecha Inspeccion", 
 "Nro. Inspeccion", ""
 "Frigorifico", 
 "Camara", 
 "Banda", 
 "Posicion", 
 "Piso", 
 "Categoria Real", 
 "Categoria Rotulada", 
 "OP", 
 "Etiqueta", 
 "Embalaje", 
 "Peso", 
 "Dimension", 
 "Tipo Envase", 
 "Mercado", 
 "Submercado", 
 "Pais", 
 "Situacion", 
 "Recibidor", 
 "Contramarca", 
 "       OV", 
 "               "
 "Fumigado", 
 "Especie   ", 
 "Grupo", 
 "Subgrupo", 
 "Variedad Real", 
 "Variedad Rotulada", 
 "OT", 
 "Linea OT", 
 "Zona", 
 "Productor", 
 "Calibre", 
 "Condicion", 
 "Tipo Frio", 
 "Tipo Frio Real", 
 "Movimiento", 
 "Fecha Cosecha", 
 "Informado", 
 "Planilla CKU", 
 "Guia Productor", 
 "Cajas", 
 "Fecha Embalaje", 
 "Restriccion SAG", 
 "Modulo", 
 "Tipo Despacho", 
 "Fecha Despacho", 
 "Nave", 
 "Cliente", 
 "Destino", 
 "Primer Pais Inspeccion", 
 "Segundo Pais Inspeccion", 
 "Standard de Consumo", 
 "Pallet CHEP", 
 "Guia/Factura", 
 "Tipo Camion", 
 "Zona Embalaje", 
 "Provincia Huerto", 
 "Comuna Huerto", 
 "Tratamiento Fosfina", 
 "Folio Recibidor", 
 "SDP    ", 
 "CZona", 
 "CProductor", 
 "Observacion Deteccion", 
 "Lobesia", 
 "Residuo", 
 "Otros", 
 "CZonaRot", 
 "CProductorRot", 
 "Productor Rot", 
 "Caract.Proceso", 
 "Desc.Cara.Proc", 
 "CSG      ", 
 "IDG      ", 
 "Contenedor", 
 "Nro.Trat.Fosfina", 
 "CSP", 
 "Calibre Rot.", 
 "CSG Rot.", 
 ""]